"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getNormalizedGridStep = exports.getNormalizedGridSize = exports.getNormalizedZoom = exports.canChangeRoundness = exports.canHaveArrowheads = exports.hasStrokeStyle = exports.hasStrokeWidth = exports.hasBackground = exports.calculateScrollCenter = exports.getTargetElements = exports.getSelectedElements = exports.getElementsWithinSelection = exports.isSomeElementSelected = void 0;
var element_1 = require("@excalidraw/element");
Object.defineProperty(exports, "isSomeElementSelected", { enumerable: true, get: function () { return element_1.isSomeElementSelected; } });
Object.defineProperty(exports, "getElementsWithinSelection", { enumerable: true, get: function () { return element_1.getElementsWithinSelection; } });
Object.defineProperty(exports, "getSelectedElements", { enumerable: true, get: function () { return element_1.getSelectedElements; } });
Object.defineProperty(exports, "getTargetElements", { enumerable: true, get: function () { return element_1.getTargetElements; } });
var scroll_1 = require("./scroll");
Object.defineProperty(exports, "calculateScrollCenter", { enumerable: true, get: function () { return scroll_1.calculateScrollCenter; } });
var element_2 = require("@excalidraw/element");
Object.defineProperty(exports, "hasBackground", { enumerable: true, get: function () { return element_2.hasBackground; } });
Object.defineProperty(exports, "hasStrokeWidth", { enumerable: true, get: function () { return element_2.hasStrokeWidth; } });
Object.defineProperty(exports, "hasStrokeStyle", { enumerable: true, get: function () { return element_2.hasStrokeStyle; } });
Object.defineProperty(exports, "canHaveArrowheads", { enumerable: true, get: function () { return element_2.canHaveArrowheads; } });
Object.defineProperty(exports, "canChangeRoundness", { enumerable: true, get: function () { return element_2.canChangeRoundness; } });
var normalize_1 = require("./normalize");
Object.defineProperty(exports, "getNormalizedZoom", { enumerable: true, get: function () { return normalize_1.getNormalizedZoom; } });
Object.defineProperty(exports, "getNormalizedGridSize", { enumerable: true, get: function () { return normalize_1.getNormalizedGridSize; } });
Object.defineProperty(exports, "getNormalizedGridStep", { enumerable: true, get: function () { return normalize_1.getNormalizedGridStep; } });
