"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.actionFlipVertical = exports.actionFlipHorizontal = exports.distributeVertically = exports.distributeHorizontally = exports.actionAlignHorizontallyCentered = exports.actionAlignVerticallyCentered = exports.actionAlignRight = exports.actionAlignLeft = exports.actionAlignBottom = exports.actionAlignTop = exports.actionAddToLibrary = exports.actionGoToCollaborator = exports.actionUngroup = exports.actionGroup = exports.actionShortcuts = exports.actionPasteStyles = exports.actionCopyStyles = exports.actionLoadScene = exports.actionSaveFileToDisk = exports.actionSaveToActiveFile = exports.actionChangeExportBackground = exports.actionChangeProjectName = exports.actionDeselect = exports.actionFinalize = exports.actionSetEmbeddableAsActiveTool = exports.actionToggleTheme = exports.actionZoomToFit = exports.actionResetZoom = exports.actionZoomOut = exports.actionZoomIn = exports.actionClearCanvas = exports.actionChangeViewBackgroundColor = exports.actionChangeArrowProperties = exports.actionChangeVerticalAlign = exports.actionChangeTextAlign = exports.actionChangeFontFamily = exports.actionChangeFontSize = exports.actionChangeOpacity = exports.actionChangeSloppiness = exports.actionChangeFillStyle = exports.actionChangeStrokeWidth = exports.actionChangeBackgroundColor = exports.actionChangeStrokeColor = exports.actionDuplicateSelection = exports.actionSelectAll = exports.actionSendToBack = exports.actionSendBackward = exports.actionBringToFront = exports.actionBringForward = exports.actionDeleteSelected = void 0;
exports.actionToggleCropEditor = exports.actionToggleSearchMenu = exports.actionToggleLinearEditor = exports.actionToggleElementLock = exports.actionLink = exports.actionBindText = exports.actionUnbindText = exports.actionToggleStats = exports.actionToggleMidpointSnapping = exports.actionToggleArrowBinding = exports.actionToggleObjectsSnapMode = exports.actionToggleZenMode = exports.actionToggleGridMode = exports.copyText = exports.actionCopyAsSvg = exports.actionCopyAsPng = exports.actionCut = exports.actionCopy = void 0;
var actionDeleteSelected_1 = require("./actionDeleteSelected");
Object.defineProperty(exports, "actionDeleteSelected", { enumerable: true, get: function () { return actionDeleteSelected_1.actionDeleteSelected; } });
var actionZindex_1 = require("./actionZindex");
Object.defineProperty(exports, "actionBringForward", { enumerable: true, get: function () { return actionZindex_1.actionBringForward; } });
Object.defineProperty(exports, "actionBringToFront", { enumerable: true, get: function () { return actionZindex_1.actionBringToFront; } });
Object.defineProperty(exports, "actionSendBackward", { enumerable: true, get: function () { return actionZindex_1.actionSendBackward; } });
Object.defineProperty(exports, "actionSendToBack", { enumerable: true, get: function () { return actionZindex_1.actionSendToBack; } });
var actionSelectAll_1 = require("./actionSelectAll");
Object.defineProperty(exports, "actionSelectAll", { enumerable: true, get: function () { return actionSelectAll_1.actionSelectAll; } });
var actionDuplicateSelection_1 = require("./actionDuplicateSelection");
Object.defineProperty(exports, "actionDuplicateSelection", { enumerable: true, get: function () { return actionDuplicateSelection_1.actionDuplicateSelection; } });
var actionProperties_1 = require("./actionProperties");
Object.defineProperty(exports, "actionChangeStrokeColor", { enumerable: true, get: function () { return actionProperties_1.actionChangeStrokeColor; } });
Object.defineProperty(exports, "actionChangeBackgroundColor", { enumerable: true, get: function () { return actionProperties_1.actionChangeBackgroundColor; } });
Object.defineProperty(exports, "actionChangeStrokeWidth", { enumerable: true, get: function () { return actionProperties_1.actionChangeStrokeWidth; } });
Object.defineProperty(exports, "actionChangeFillStyle", { enumerable: true, get: function () { return actionProperties_1.actionChangeFillStyle; } });
Object.defineProperty(exports, "actionChangeSloppiness", { enumerable: true, get: function () { return actionProperties_1.actionChangeSloppiness; } });
Object.defineProperty(exports, "actionChangeOpacity", { enumerable: true, get: function () { return actionProperties_1.actionChangeOpacity; } });
Object.defineProperty(exports, "actionChangeFontSize", { enumerable: true, get: function () { return actionProperties_1.actionChangeFontSize; } });
Object.defineProperty(exports, "actionChangeFontFamily", { enumerable: true, get: function () { return actionProperties_1.actionChangeFontFamily; } });
Object.defineProperty(exports, "actionChangeTextAlign", { enumerable: true, get: function () { return actionProperties_1.actionChangeTextAlign; } });
Object.defineProperty(exports, "actionChangeVerticalAlign", { enumerable: true, get: function () { return actionProperties_1.actionChangeVerticalAlign; } });
Object.defineProperty(exports, "actionChangeArrowProperties", { enumerable: true, get: function () { return actionProperties_1.actionChangeArrowProperties; } });
var actionCanvas_1 = require("./actionCanvas");
Object.defineProperty(exports, "actionChangeViewBackgroundColor", { enumerable: true, get: function () { return actionCanvas_1.actionChangeViewBackgroundColor; } });
Object.defineProperty(exports, "actionClearCanvas", { enumerable: true, get: function () { return actionCanvas_1.actionClearCanvas; } });
Object.defineProperty(exports, "actionZoomIn", { enumerable: true, get: function () { return actionCanvas_1.actionZoomIn; } });
Object.defineProperty(exports, "actionZoomOut", { enumerable: true, get: function () { return actionCanvas_1.actionZoomOut; } });
Object.defineProperty(exports, "actionResetZoom", { enumerable: true, get: function () { return actionCanvas_1.actionResetZoom; } });
Object.defineProperty(exports, "actionZoomToFit", { enumerable: true, get: function () { return actionCanvas_1.actionZoomToFit; } });
Object.defineProperty(exports, "actionToggleTheme", { enumerable: true, get: function () { return actionCanvas_1.actionToggleTheme; } });
var actionEmbeddable_1 = require("./actionEmbeddable");
Object.defineProperty(exports, "actionSetEmbeddableAsActiveTool", { enumerable: true, get: function () { return actionEmbeddable_1.actionSetEmbeddableAsActiveTool; } });
var actionFinalize_1 = require("./actionFinalize");
Object.defineProperty(exports, "actionFinalize", { enumerable: true, get: function () { return actionFinalize_1.actionFinalize; } });
var actionDeselect_1 = require("./actionDeselect");
Object.defineProperty(exports, "actionDeselect", { enumerable: true, get: function () { return actionDeselect_1.actionDeselect; } });
var actionExport_1 = require("./actionExport");
Object.defineProperty(exports, "actionChangeProjectName", { enumerable: true, get: function () { return actionExport_1.actionChangeProjectName; } });
Object.defineProperty(exports, "actionChangeExportBackground", { enumerable: true, get: function () { return actionExport_1.actionChangeExportBackground; } });
Object.defineProperty(exports, "actionSaveToActiveFile", { enumerable: true, get: function () { return actionExport_1.actionSaveToActiveFile; } });
Object.defineProperty(exports, "actionSaveFileToDisk", { enumerable: true, get: function () { return actionExport_1.actionSaveFileToDisk; } });
Object.defineProperty(exports, "actionLoadScene", { enumerable: true, get: function () { return actionExport_1.actionLoadScene; } });
var actionStyles_1 = require("./actionStyles");
Object.defineProperty(exports, "actionCopyStyles", { enumerable: true, get: function () { return actionStyles_1.actionCopyStyles; } });
Object.defineProperty(exports, "actionPasteStyles", { enumerable: true, get: function () { return actionStyles_1.actionPasteStyles; } });
var actionMenu_1 = require("./actionMenu");
Object.defineProperty(exports, "actionShortcuts", { enumerable: true, get: function () { return actionMenu_1.actionShortcuts; } });
var actionGroup_1 = require("./actionGroup");
Object.defineProperty(exports, "actionGroup", { enumerable: true, get: function () { return actionGroup_1.actionGroup; } });
Object.defineProperty(exports, "actionUngroup", { enumerable: true, get: function () { return actionGroup_1.actionUngroup; } });
var actionNavigate_1 = require("./actionNavigate");
Object.defineProperty(exports, "actionGoToCollaborator", { enumerable: true, get: function () { return actionNavigate_1.actionGoToCollaborator; } });
var actionAddToLibrary_1 = require("./actionAddToLibrary");
Object.defineProperty(exports, "actionAddToLibrary", { enumerable: true, get: function () { return actionAddToLibrary_1.actionAddToLibrary; } });
var actionAlign_1 = require("./actionAlign");
Object.defineProperty(exports, "actionAlignTop", { enumerable: true, get: function () { return actionAlign_1.actionAlignTop; } });
Object.defineProperty(exports, "actionAlignBottom", { enumerable: true, get: function () { return actionAlign_1.actionAlignBottom; } });
Object.defineProperty(exports, "actionAlignLeft", { enumerable: true, get: function () { return actionAlign_1.actionAlignLeft; } });
Object.defineProperty(exports, "actionAlignRight", { enumerable: true, get: function () { return actionAlign_1.actionAlignRight; } });
Object.defineProperty(exports, "actionAlignVerticallyCentered", { enumerable: true, get: function () { return actionAlign_1.actionAlignVerticallyCentered; } });
Object.defineProperty(exports, "actionAlignHorizontallyCentered", { enumerable: true, get: function () { return actionAlign_1.actionAlignHorizontallyCentered; } });
var actionDistribute_1 = require("./actionDistribute");
Object.defineProperty(exports, "distributeHorizontally", { enumerable: true, get: function () { return actionDistribute_1.distributeHorizontally; } });
Object.defineProperty(exports, "distributeVertically", { enumerable: true, get: function () { return actionDistribute_1.distributeVertically; } });
var actionFlip_1 = require("./actionFlip");
Object.defineProperty(exports, "actionFlipHorizontal", { enumerable: true, get: function () { return actionFlip_1.actionFlipHorizontal; } });
Object.defineProperty(exports, "actionFlipVertical", { enumerable: true, get: function () { return actionFlip_1.actionFlipVertical; } });
var actionClipboard_1 = require("./actionClipboard");
Object.defineProperty(exports, "actionCopy", { enumerable: true, get: function () { return actionClipboard_1.actionCopy; } });
Object.defineProperty(exports, "actionCut", { enumerable: true, get: function () { return actionClipboard_1.actionCut; } });
Object.defineProperty(exports, "actionCopyAsPng", { enumerable: true, get: function () { return actionClipboard_1.actionCopyAsPng; } });
Object.defineProperty(exports, "actionCopyAsSvg", { enumerable: true, get: function () { return actionClipboard_1.actionCopyAsSvg; } });
Object.defineProperty(exports, "copyText", { enumerable: true, get: function () { return actionClipboard_1.copyText; } });
var actionToggleGridMode_1 = require("./actionToggleGridMode");
Object.defineProperty(exports, "actionToggleGridMode", { enumerable: true, get: function () { return actionToggleGridMode_1.actionToggleGridMode; } });
var actionToggleZenMode_1 = require("./actionToggleZenMode");
Object.defineProperty(exports, "actionToggleZenMode", { enumerable: true, get: function () { return actionToggleZenMode_1.actionToggleZenMode; } });
var actionToggleObjectsSnapMode_1 = require("./actionToggleObjectsSnapMode");
Object.defineProperty(exports, "actionToggleObjectsSnapMode", { enumerable: true, get: function () { return actionToggleObjectsSnapMode_1.actionToggleObjectsSnapMode; } });
var actionToggleArrowBinding_1 = require("./actionToggleArrowBinding");
Object.defineProperty(exports, "actionToggleArrowBinding", { enumerable: true, get: function () { return actionToggleArrowBinding_1.actionToggleArrowBinding; } });
var actionToggleMidpointSnapping_1 = require("./actionToggleMidpointSnapping");
Object.defineProperty(exports, "actionToggleMidpointSnapping", { enumerable: true, get: function () { return actionToggleMidpointSnapping_1.actionToggleMidpointSnapping; } });
var actionToggleStats_1 = require("./actionToggleStats");
Object.defineProperty(exports, "actionToggleStats", { enumerable: true, get: function () { return actionToggleStats_1.actionToggleStats; } });
var actionBoundText_1 = require("./actionBoundText");
Object.defineProperty(exports, "actionUnbindText", { enumerable: true, get: function () { return actionBoundText_1.actionUnbindText; } });
Object.defineProperty(exports, "actionBindText", { enumerable: true, get: function () { return actionBoundText_1.actionBindText; } });
var actionLink_1 = require("./actionLink");
Object.defineProperty(exports, "actionLink", { enumerable: true, get: function () { return actionLink_1.actionLink; } });
var actionElementLock_1 = require("./actionElementLock");
Object.defineProperty(exports, "actionToggleElementLock", { enumerable: true, get: function () { return actionElementLock_1.actionToggleElementLock; } });
var actionLinearEditor_1 = require("./actionLinearEditor");
Object.defineProperty(exports, "actionToggleLinearEditor", { enumerable: true, get: function () { return actionLinearEditor_1.actionToggleLinearEditor; } });
var actionToggleSearchMenu_1 = require("./actionToggleSearchMenu");
Object.defineProperty(exports, "actionToggleSearchMenu", { enumerable: true, get: function () { return actionToggleSearchMenu_1.actionToggleSearchMenu; } });
var actionCropEditor_1 = require("./actionCropEditor");
Object.defineProperty(exports, "actionToggleCropEditor", { enumerable: true, get: function () { return actionCropEditor_1.actionToggleCropEditor; } });
