export const CODEX_INTEGRATION_MANIFEST_SCHEMA_VERSION = 1;
export const CODEX_INTEGRATION_VERSION = "1.13.2";
export const CODEX_LEGACY_INTEGRATION_VERSION = "1.0.0";
export const CODEX_INTEGRATION_SKILL_VERSION = 20;
export const CODEX_INTEGRATION_CLI_WRAPPER_VERSION = 1;
